"""Write translated functions as C++ source files."""

import os

from . import arm


WRITTEN = []


def write_if_changed(path, text):
    WRITTEN.append(path)
    try:
        with open(path) as fp:
            if fp.read() == text:
                return
    except FileNotFoundError:
        pass
    with open(path, 'w') as fp:
        fp.write(text)
from .analysis import explore, next_key

HEADER = '''// Generated by PokemonSunNative's recompiler from the user's own game image. Do not edit.
#include <recomp/rt.h>
using namespace recomp;
'''


def fname(img, key):
    return f'f{img.index}_{key:x}'


def label(key):
    return f'L_{key:x}'


class FunctionWriter:
    def __init__(self, img, dec, entries, f):
        self.img = img
        self.dec = dec
        self.entries = entries
        self.f = f
        self.out = []
        self.refs = set()  # other functions referenced

    def w(self, s):
        self.out.append(s)

    def target_fn(self, key):
        if key in self.entries:
            self.refs.add(key)
            return fname(self.img, key)
        return None

    def jump_code(self, insn, indent):
        t = 'c->t = tgt & 1; tgt &= c->t ? ~1u : ~3u;' if insn.interwork else \
            ('tgt &= ~1u;' if insn.thumb else 'tgt &= ~3u;')
        return [f'{indent}{t}', f'{indent}c->r[15] = tgt;',
                f'{indent}if ((tgt | c->t) == ret_expect) return;', f'{indent}goto dispatch;']

    def addr(self, a):
        return self.dec.ctx.addr(a)

    def insn_code(self, k, insn):
        lines = []
        ind = '        '
        kind = insn.kind
        nk = next_key(insn)
        if kind == 'undef':
            return [f'    undefined(c, {self.addr(insn.addr)}, 0x{insn.word:X}u); // {insn.text}']
        body = [ind + s for s in insn.body]
        if kind == 'op':
            lines += body
        elif kind == 'svc':
            lines.append(f'{ind}svc(c, 0x{insn.imm:X}u, {self.addr(insn.end)});')
        elif kind == 'b':
            t = insn.target
            fn = self.target_fn(t) if t in self.f.tails else None
            if fn:
                lines.append(f'{ind}[[clang::musttail]] return {fn}(c);')
            elif t in self.f.insns:
                lines.append(f'{ind}goto {label(t)};')
            else:
                lines.append(f'{ind}undefined(c, {self.addr(t & ~1)}, 1);')
        elif kind == 'bl':
            ret = insn.end | (1 if insn.thumb else 0)
            fn = self.target_fn(insn.target)
            lines.append(f'{ind}c->r[14] = {self.addr(ret)};')
            if fn:
                lines.append(f'{ind}{fn}(c);')
            else:
                lines.append(f'{ind}call(c, {self.addr(insn.target)});')
            lines.append(f'{ind}if (RT_UNLIKELY((c->r[15] | c->t) != {self.addr(ret)})) goto dispatch;')
        elif kind == 'callr':
            ret = insn.end | (1 if insn.thumb else 0)
            lines += body
            lines.append(f'{ind}c->r[14] = {self.addr(ret)};')
            lines.append(f'{ind}call(c, tgt);')
            lines.append(f'{ind}if (RT_UNLIKELY((c->r[15] | c->t) != {self.addr(ret)})) goto dispatch;')
        elif kind == 'jump':
            jt = self.f.tables.get(k)
            lines += body
            if jt:
                reg, targets, _ = jt
                lines.append(f'{ind}switch (c->r[{reg}]) {{')
                for i, t in enumerate(targets):
                    lines.append(f'{ind}case {i}: goto {label(t)};')
                lines.append(f'{ind}}}')
            lines += self.jump_code(insn, ind)
        else:
            raise ValueError(kind)
        cond = insn.cond
        head = f'    // {insn.addr:08x}: {insn.word:08x} {insn.text}'
        if cond == 14:
            return [head, '    {'] + lines + ['    }']
        return [head, f'    if ({arm.COND_EXPR[cond]}) {{'] + lines + ['    }']

    def write(self):
        img, f = self.img, self.f
        key = f.key
        name = fname(img, key)
        self.w(f'void {name}(Cpu* c) {{')
        self.w('    const u32 ret_expect = c->r[14];')
        if img.module_relative:
            self.w(f'    const u32 MB = mod_base[{img.index}];')
        else:
            self.w('    constexpr u32 MB = 0;')
        self.w(f'    c->t = {key & 1};')
        self.w('    u32 tgt;')
        self.w('    (void)tgt;')
        self.w('    if (RT_UNLIKELY(c->resume)) { c->resume = 0; goto dispatch; }')
        self.w(f'    goto {label(key)};')
        keys = sorted(f.insns)
        # Labels: entry, branch targets, post-call points, jump table cases. Ticks are charged at
        # each label for the straight-line run that follows it.
        labels = set(f.labels)
        for i, k in enumerate(keys):
            insn = f.insns[k]
            if insn is None:
                continue
            nk = next_key(insn)
            falls = not (insn.cond == 14 and insn.kind in ('b', 'jump', 'undef'))
            if falls and k not in f.falls and (i + 1 >= len(keys) or keys[i + 1] != nk):
                labels.add(nk)
        for i, k in enumerate(keys):
            insn = f.insns[k]
            if k in labels:
                run = 0
                for k2 in keys[i:]:
                    if k2 != k and k2 in labels:
                        break
                    ins2 = f.insns[k2]
                    if ins2 is None:
                        break
                    run += ins2.ticks
                    if ins2.cond == 14 and ins2.kind in ('b', 'jump', 'undef'):
                        break
                self.w(f'{label(k)}:')
                if run:
                    self.w(f'    tick(c, {run});')
            if insn is None:
                self.w(f'    undefined(c, {self.addr(k & ~1)}, 2);')
                continue
            self.out += self.insn_code(k, insn)
            nk = next_key(insn)
            falls = not (insn.cond == 14 and insn.kind in ('b', 'jump', 'undef'))
            if k in f.falls:
                self.w(f'    [[clang::musttail]] return {self.target_fn(f.falls[k])}(c);')
            elif falls and (i + 1 >= len(keys) or keys[i + 1] != nk):
                if nk in f.insns:
                    self.w(f'    goto {label(nk)};')
                else:
                    self.w(f'    undefined(c, {self.addr(nk & ~1)}, 3);')
        self.w('dispatch:')
        self.w('    switch ((c->r[15] | c->t) - MB) {')
        for k in sorted(labels):
            if k in f.insns:
                self.w(f'    case 0x{k:X}u: goto {label(k)};')
        self.w('    }')
        self.w('    if (HostFn fn = lookup(c->r[15] | c->t)) {')
        self.w('        [[clang::musttail]] return fn(c);')
        self.w('    }')
        self.w('}')
        self.labels = sorted(k for k in labels if k in f.insns)
        return self.out


def write_image(img, dec, entries, outdir, insns_per_file=40000, log=print):
    """Translate every function of `img`. Returns (entries, labels) lists of keys."""
    files = []
    chunk, chunk_refs, chunk_defs, count = [], set(), set(), 0
    all_labels = {}
    n = 0

    def flush():
        nonlocal chunk, chunk_refs, chunk_defs, count
        if not chunk:
            return
        path = os.path.join(outdir, f'img{img.index}_{len(files):03d}.cpp')
        parts = [HEADER]
        for r in sorted(chunk_refs | chunk_defs):
            parts.append(f'void {fname(img, r)}(Cpu* c);\n')
        parts.append('\n'.join(chunk))
        parts.append('\n')
        write_if_changed(path, ''.join(parts))
        files.append(path)
        chunk, chunk_refs, chunk_defs, count = [], set(), set(), 0

    for key in sorted(entries):
        f = explore(dec, key, entries, discover=False)
        fw = FunctionWriter(img, dec, entries, f)
        code = fw.write()
        chunk.append('\n'.join(code))
        chunk_refs |= fw.refs
        chunk_defs.add(key)
        for lk in fw.labels:
            all_labels.setdefault(lk, key)
        count += len(f.insns)
        n += len(f.insns)
        if count >= insns_per_file:
            flush()
    flush()
    cov = getattr(dec, 'coverage', 0) * 100
    log(f'  {img.name}: {len(entries)} functions, {n} instructions, {cov:.1f}% of code covered, '
        f'{len(files)} files')
    return files, all_labels


def write_tables(images, results, outdir):
    path = os.path.join(outdir, 'tables.cpp')
    out = [HEADER, '#include <recomp/tables.h>\n\n']
    for img, (entries, labels) in zip(images, results):
        for key in sorted(entries):
            out.append(f'void {fname(img, key)}(Cpu* c);\n')
    out.append('\nnamespace recomp {\n')
    out.append(f'u32 mod_base[{len(images)}];\n')
    for img, (entries, labels) in zip(images, results):
        out.append(f'static const Entry entries{img.index}[] = {{\n')
        for key in sorted(entries):
            out.append(f'    {{0x{key:X}u, ::{fname(img, key)}}},\n')
        out.append('    {0xFFFFFFFFu, nullptr},\n};\n')
        out.append(f'static const Entry labels{img.index}[] = {{\n')
        for lk, fk in sorted(labels.items()):
            out.append(f'    {{0x{lk:X}u, ::{fname(img, fk)}}},\n')
        out.append('    {0xFFFFFFFFu, nullptr},\n};\n')
    out.append(f'const ImageInfo images[{len(images)}] = {{\n')
    for img, (entries, labels) in zip(images, results):
        s, e = img.code_ranges[0]
        out.append(f'    {{"{img.name}", {"true" if img.module_relative else "false"}, 0x{s:X}u, 0x{e:X}u, '
                   f'entries{img.index}, {len(entries)}, labels{img.index}, {len(labels)}}},\n')
    out.append('};\n')
    out.append(f'const u32 num_images = {len(images)};\n')
    out.append('} // namespace recomp\n')
    write_if_changed(path, ''.join(out))
    return path
